Letâ€™s begin by installing and importing the necessary packages\libraries. This is a fundamental step required in every exploratory data analysis process.

In [24]:
# Install sodapy
# Sodapy is a python client for the Socrata Open Data API.
!pip install sodapy

Requirement already satisfied: sodapy in c:\users\tharasan\anaconda3\lib\site-packages (2.1.0)
Requirement already satisfied: requests>=2.20.0 in c:\users\tharasan\anaconda3\lib\site-packages (from sodapy) (2.22.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tharasan\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\tharasan\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\tharasan\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\tharasan\anaconda3\lib\site-packages (from requests>=2.20.0->sodapy) (1.25.8)

In [25]:
import pandas as pd
import numpy as np
from sodapy import Socrata
import seaborn as sns
from matplotlib import pyplot as plt

###### Loading the dataset from an API endpoint using sodapy

In [26]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password
client = Socrata("data.cincinnati-oh.gov", None)
# Entire records returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results_cincinnati = client.get("vnsz-a3wp", limit=492500)
# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results_cincinnati)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

###### Initial exploration to understand and summarize the dataset

In [27]:
# how many rows and columns given dataset consists
print("Cincinnati 911 dataset contains ", results_df.shape[0], " rows and " , results_df.shape[1], "columns.")

Cincinnati 911 dataset contains  492500  rows and  17 columns.

###### Explore the first few rows of the dataset

In [28]:
# reading first five rows
results_df.head()

,address_x,latitude_x,longitude_x,agency,create_time_incident,disposition_text,event_number,incident_type_id,incident_type_desc,neighborhood,arrival_time_primary_unit,beat,closed_time_incident,dispatch_time_primary_unit,cfd_incident_type,cfd_incident_type_group,community_council_neighborhood
0,PRESIDENT DR,39.1534720000896,-84.560768,CFD,2020-09-01T16:45:57.000,MED: MT RESPONSE NO TRANSPORT,CFD200901000147,29A1,1ST PARTY CALLER WITH INJURY TO NOT DANGEROUS ...,VILLAGES AT ROLL HILL,2020-09-01T16:54:08.000,ST12,2020-09-01T17:04:49.000,2020-09-01T16:50:28.000,BLS,TRAFFIC / TRANSPORTATION INCIDENTS,VILLAGES AT ROLL HILL
1,HIGHLAND AV / RIDGE RD,39.1702690000896,-84.426011,CFD,2020-04-09T09:10:59.000,MED: MT RESPONSE NO TRANSPORT,CFD200409000078,29A1,1ST PARTY CALLER WITH INJURY TO NOT DANGEROUS ...,N/A,2020-04-09T09:18:50.000,OTHER JURIS 8,2020-04-09T09:19:15.000,2020-04-09T09:11:10.000,BLS,TRAFFIC / TRANSPORTATION INCIDENTS,N/A
2,CLIFTON AV / W MARTIN LUTHER KING JR DR,39.1350670000896,-84.519264,CFD,2020-01-10T16:18:16.000,"EMS: NO TRANSPORT,IN: INVESTIG",CFD200110000136,29A1,1ST PARTY CALLER WITH INJURY TO NOT DANGEROUS ...,CUF,2020-01-10T16:18:47.000,ST34,2020-01-10T16:33:53.000,2020-01-10T16:18:47.000,BLS,TRAFFIC / TRANSPORTATION INCIDENTS,CORRYVILLE - HEIGHTS
3,VINE ST,39.1039320000897,-84.514527,CFD,2019-12-27T17:41:30.000,MEDT: MEDIC TRANSPORT,CFD191227000180,29A1,1ST PARTY CALLER WITH INJURY TO NOT DANGEROUS ...,DOWNTOWN,2019-12-27T17:45:12.000,ST03,2019-12-27T18:24:43.000,2019-12-27T17:42:14.000,BLS,TRAFFIC / TRANSPORTATION INCIDENTS,DOWNTOWN
4,N I75 TO EXIT 1B,39.0962690000897,-84.521328,CFD,2019-10-21T19:01:00.000,MEDT: MEDIC TRANSPORT,CFD191021000218,29A1,1ST PARTY CALLER WITH INJURY TO NOT DANGEROUS ...,DOWNTOWN,2019-10-21T19:06:17.000,ST14,2019-10-21T19:48:01.000,2019-10-21T19:01:42.000,BLS,TRAFFIC / TRANSPORTATION INCIDENTS,DOWNTOWN

###### Look at the date range of the dataset

In [29]:
print(results_df.create_time_incident.min())
print(results_df.create_time_incident.max())

2015-01-01T00:02:52.000
2020-11-13T00:07:34.000

###### Statistical description of numerical data

In [30]:
# gives the statistical result of all numerical column present in dataset
results_df.describe()

,address_x,latitude_x,longitude_x,agency,create_time_incident,disposition_text,event_number,incident_type_id,incident_type_desc,neighborhood,arrival_time_primary_unit,beat,closed_time_incident,dispatch_time_primary_unit,cfd_incident_type,cfd_incident_type_group,community_council_neighborhood
count,492412,468959,468959,492500,492500,489456,492500,490897,333958,492500,419665,491972,487676,446317,479236,479227,492500
unique,16737,302341,273527,2,491676,221,492498,695,623,51,419223,554,486923,446261,6,107,72
top,READING RD,39.1060190000598,-84.52617,CFD,2016-11-06T21:19:33.000,MEDT: MEDIC TRANSPORT,CFD180110000001,FALARM,DIFFICULTY SPEAKING BETWEEN BREATHS,WESTWOOD,2017-12-31T18:52:39.000,ST35,2017-02-07T18:09:30.000,2019-07-12T09:14:32.000,ALS,SICK PERSON,WESTWOOD
freq,12161,19,20,326529,3,133562,2,31223,18060,37581,4,24052,5,2,200247,48503,38038

###### Statistical description of categorical data

In [31]:
# printing index of all categorical data
categorical=results_df.dtypes[results_df.dtypes==object].index   
# stats description of categorical data
results_df[categorical].describe()

,address_x,latitude_x,longitude_x,agency,create_time_incident,disposition_text,event_number,incident_type_id,incident_type_desc,neighborhood,arrival_time_primary_unit,beat,closed_time_incident,dispatch_time_primary_unit,cfd_incident_type,cfd_incident_type_group,community_council_neighborhood
count,492412,468959,468959,492500,492500,489456,492500,490897,333958,492500,419665,491972,487676,446317,479236,479227,492500
unique,16737,302341,273527,2,491676,221,492498,695,623,51,419223,554,486923,446261,6,107,72
top,READING RD,39.1060190000598,-84.52617,CFD,2016-11-06T21:19:33.000,MEDT: MEDIC TRANSPORT,CFD180110000001,FALARM,DIFFICULTY SPEAKING BETWEEN BREATHS,WESTWOOD,2017-12-31T18:52:39.000,ST35,2017-02-07T18:09:30.000,2019-07-12T09:14:32.000,ALS,SICK PERSON,WESTWOOD
freq,12161,19,20,326529,3,133562,2,31223,18060,37581,4,24052,5,2,200247,48503,38038

###### Checking whether null value is present in given dataset or not

In [32]:
# is null value present or not?
results_df.isnull().values.any()  

# total number of null value in each column
results_df.isnull().sum()

address_x                             88
latitude_x                         23541
longitude_x                        23541
agency                                 0
create_time_incident                   0
disposition_text                    3044
event_number                           0
incident_type_id                    1603
incident_type_desc                158542
neighborhood                           0
arrival_time_primary_unit          72835
beat                                 528
closed_time_incident                4824
dispatch_time_primary_unit         46183
cfd_incident_type                  13264
cfd_incident_type_group            13273
community_council_neighborhood         0
dtype: int64

###### understanding a few target column

In [33]:
results_df.incident_type_id.unique()

array(['29A1', '24A1', '24C2', '24C1', '24D4', '911CALL', '1A1', '24C3',
       '1D1', '1D0', '1C3', '1C4', '1C6', '1C2', '1C5', '1C0', '1C1',
       '13C2', '13C2C', '26C2', '6C1', '13C3', '21D5', '10C1', '23C2',
       '18C2', '6C1A', '6C1E', '6C1O', '28C2', '23C2I', '19C2', '15D8',
       '23C2V', '13C3C', '11D1', '36C2A', '36C2S', '36C2B', '36C2C',
       '36C1A', '36C1S', '23C6V', '23C6', '12D3', 'AIRF', '20A1', '13A1',
       '15C1', '14B1', '14A1', '31C1', '14C1', '8C1', '8B1', '2C2', '2E1',
       '2D1', '2D0', '2D4', '2D3', '2C1', '2D2', '2A1', '2A2', '2B1',
       '26C1', '3D7', '3D4', '3D5', '3A2', '3D2', '3A1', '3B1', '3B2',
       '3A3', '3D1', '3B3', '23C3I', '23C3', '27D1G', '21D1', '17D2',
       '27D1S', '29D6', '30D1', '8D1', '4D1', '14E1', '1D2', '5D2',
       '4D3A', '4D4A', '4A2A', '4D2A', '4A1A', '4B1A', '4B2A', '4D1A',
       '4B3A', 'ASSLTF', '3D9', 'SUICF', '12C7', 'BLDGF', 'ACCIF', '26C4',
       '24D6', '24D7', '24C4', '5C3', '5C2', '5A2', '5A1', '5D1', '5C1',
       'BIOHZF', '7B2', '7B1', '21B3', '26A2', '21B4', 'BOATF', '26O2',
       'BOMB', 'BOMBF', '18A1', '10A2', '10A1', '10C3', '28C11', '28A1',
       '6D1A', '6D0A', '6D2A', '6D4A', '6D3A', '6E1A', '6D3', '6D4',
       '6D2', '6E1', '6D1', '6D0', '24D1', '26O3', '7A1', '7C3', '7C2',
       '7D4', '7D3', '7D2', '7A3', '7E1', '7C4', '32B4', '26O4', '26O5',
       'CALARM', '8O2', 'COSICK', '19C4', '9B0', '9B1', '9O1', '9E1',
       '9D1', '9E2', '9E6', '9E3', '9E0', '9E5', '9D2', '9E4', '26O6',
       '27D4G', '27D4S', '27D4P', '18C7', '20B1', '23D2I', '31D4', '23D2',
       '19D3', '6D3O', '10D3', '6D3E', '36D4A', '36D4S', '36D4B', 'CHEMI',
       'CHEMF', '17D5', '4D4', '30D4', '10C4', '10D4', '10D2', '19C3',
       '36A2B', '36A2A', '36A2S', '36C4A', '36C4S', '19A2', '36A1A',
       '36A1S', '36C3A', '36C3S', '36C3B', '10C2', '10D1', '10C0', '11D2',
       '11A1', '19D4', '6D4E', '6D4O', '19C5', '23C4', '23C4I', '23C4V',
       '20A1C', '20B1C', '20C1C', '20D1C', '20B2C', '11E1', '22D4',
       '26O7', '12D2', '12C1', '12A2', '12A1', '12B1', '12C5', '12C6',
       '12C3', '12C4', '12A3', '12A4', '12A5', '12C5E', '12A1E', '12C1E',
       '12C2', '12C7E', '12A5E', '12B1E', '12A4E', '12C3E', '26O8',
       '26O9', 'CUTF', '21D4', '25D2', '25D2V', '26O10', '26O11', '26O1',
       'DETAIL', '13C1', '13C1C', '13C0', '13D1', '5C4', '6D2E', '19D2',
       '6D2O', '7D5', '8D4', '36D2A', '36D2B', '36D2S', '26A3', 'DOMNF',
       'DOMINF', 'DROWNF', '14D2', '14D1', '14B2', '26O12', '12D4',
       '15D7', '15D6', '15E1', '15D2', '15D3', 'TRAPF', 'TRAP', '17D1',
       '17D1J', '16A2', '16A1', '16A3', '16D1', '16B1', '31A3', '31A2',
       '31A1', '31C2', '31C3', '31D3', 'FALARM', '17A1', '17B1', '17D4',
       '17B3J', '17A2', '17A3', '17B0', '17D0', '17B2', '17D3', '17B3',
       '26A4', 'FADV', '7A2', 'FDRILL', 'FTRACC', 'WALKIN', 'HYDR', 'FRO',
       'FSERV', '19C1', '36A3S', '36A3A', '36A3B', '36A3C', 'FHELPF',
       'FUMES', 'GAS2', 'GAS1', '26A5', '26O14', 'SIG500', '27D3G',
       '27A1G', '27D2G', '27B2G', '27B4G', '18C1', '18C5', '18C6', '18C3',
       '18C4', '18B1', '24D2', '10D5', '20C1', '19D5', '19D1', '19C6',
       '19A1', '19C7', '20A1H', '20B1H', '20C1H', '20D1H', '20B2H', 'TRK',
       '21C3', '21A2', '21B2', '21B1', '21D3', '21D2', '21A1', '21C0',
       '21C2', '21C1', '26O15', 'HERONF', 'HEROIF', '29D2', '24D5',
       '36C5A', '36C5S', '36C5B', '36C5C', '29D3', '30D5', 'HIRISE',
       'HIRISK', '24D3', 'INACTF', '31E1', '6E1E', '6E1O', '36D1A',
       '36D1S', '8D3', '29B1', 'INVEST', '26O18', '25B4', '27B2', '27B2P',
       '27B2S', '24B1', '3D6', '32D1', 'LOCK', '17D6', '17D6J', '29B4',
       '29D1', '30A1', '4A1', 'MCI', '3D8', '22D1', '32B2', 'EMS',
       'MENTIF', '4D5', '7D1', '27D5G', '27D5P', '27D5S', '27D5',
       'MUTUAL', '23C5', '23C5I', '23C5V', '26A6', '25D3', '25D3V',
       '25B5', '25B5V', '26O19', '26A7', '29O1', '29A2', '22A1', '7A5',
       '17O2', '30A3', '4A3', '27A1', '27A1P', '27B1S', '27B1P', '27B1G',
       '25B2', '25B2V', '25A1', '26A1', '28C1', '6D1E', '26D1', '23C1',
       '30D3', '23C1I', '6D1O', '23C1V', '4D3', '20D1', '14D5', '3D3',
       '25D1', '25D1V', '27D3S', '27D3P', '36D3S', '36D3A', '36D3B',
       '36D3C', '29D8', '29D9', '12D1', '4A2', '30A2', '17A2J', '26O20',
       '26O21', '27B5G', '29B3', '26A8', 'OUTDR', '23D2V', '23B1',
       '23B1I', '23B0V', '23B1V', '23B0', '23C0', '23C8', '23D1', '23D1I',
       '23C7', '23C7I', '17A0', '26A0', '10D0', '10A0', '30A0', '30D0',
       '21A0', '8B0', '3B0', '13A0', '12C0', '29A0', '26B0', '26D0',
       '20A0', '16A0', '24A0', '31D0', '26C0', '6E0', '31E0', '23D0',
       '1A0', '21D0', '23C0V', '5C0', '20B0', '18B0', '11D0', '3D0',
       '29D0', '32D0', '30B0', '9D0', '26O22', '26O23', '22B2', 'PERDWF',
       '32B1', '32B3', '29D5', '23C8V', '23C8I', '23O1', 'TASER',
       'PHELPF', 'PDOAF', '26A12', '28C6', '28C5', '28C9', '28C3', '28C4',
       '28C8', '28C7', '28C10', '28C12', '4B1', '30B1', 'POSTAF', '15D4',
       '24C0', '24B2', '24O1', '25B1', '25A2', '25B6', '17A4', 'RAPEF',
       '26O24', '22B3', 'RIVERF', 'ROBBIF', 'SALV', '12D4E', '12D2E',
       '12D1E', '4B2', '30B2', '25B1V', '27B3G', '29B2', '27B3P', '4B0S',
       '26O25', 'SHOOTF', '26C3', '26O13', '26O16', '26O26', '26O27',
       '26A9', '26B1', '26A10', '26A11', '26O28', 'VEH', 'OUTLET',
       'STILL', 'COLAPS', 'STRUCT', '7C1', 'STUCK', 'SWAT', 'INFOF',
       'FTEST', '1A2', '25B3', '25B3V', '6C2', '6C2O', '6C2E', '6C2A',
       '6D5', '6D5O', '6D5E', '29D4', '30D2', '29D7', '4D2', '13D1C',
       '27D2', '27D2S', '31D1', '31D2', '14E2', '30B3', '29B5', '4B3',
       '23C7V', '8D6', '20B2', '14B3', '25B6V', '27B4P', '27B4', 'UNK',
       'UNKF', 'WATERR', 'WIRES', 'PERDWN-COMBINED', 'SICKF-FD ONLY',
       'ACCIF-FD ONLY', 'STRUCT-COMBINED', 'SHOOT-COMBINED',
       'ACCI-COMBINED', 'HEROIN-COMBINED', 'ASSLTI-COMBINED',
       'PDOA-COMBINED', '17B4', 'DOMINJ-COMBINED', 'SUIC-COMBINED',
       'BLDGF-COMBINED', 'ROBBI-COMBINED', 'STILL-COMBINED',
       'TRAP-COMBINED', 'CUT-COMBINED', 'TRANSFER CALL',
       'PHELPF-COMBINED', '23E1', 'TEST', 'RIVER-COMBINED',
       'RAPEI-COMBINED', 'HEROINF-FIRE ONLY', 'INJF-PD REQ', '25O1',
       'TRAPF-FD ONLY', '3A4', '31D5', '27D4', 'FHELP-COMBINED',
       'DROWN-COMBINED', 'CHEM-COMBINED', 'BOMB-COMBINED', '17B4J',
       'BIOHAZ-COMBINED', '23D3V', 'CUTTING-FD ONLY', 'INACT-COMBINED',
       '23D3', '23EI1', 'COLAPS-COMBINED', 'AIR-COMBINED', '7A0', 'FIRE',
       'BOMBF-FIRE ONLY', '27D3', 'BOAT-COMBINED', 'NMUTUAL',
       'ACCF-PD PW', '4A0', '15D1', '3A0', nan, 'HEROINF - FIRE ONLY',
       'SICKF-COMBINED', 'ACCIF FIRE ONLY', '21B0', '25O2', '28C0',
       '27B1', '15D9', '11O1', 'POSTAL-COMBINED'], dtype=object)

In [34]:
results_df['cfd_incident_type'].value_counts()

ALS     200247
BLS     168110
FIRE     75787
OTHE     33285
MEDI       960
NOT        847
Name: cfd_incident_type, dtype: int64

In [35]:
results_df['neighborhood'].value_counts()

WESTWOOD                          37581
DOWNTOWN                          30947
AVONDALE                          28174
EAST PRICE HILL                   27246
N/A                               22989
WEST PRICE HILL                   21337
OVER-THE-RHINE                    20180
WEST END                          19188
WALNUT HILLS                      18451
COLLEGE HILL                      18169
MADISONVILLE                      15132
CUF                               15025
ROSELAWN                          13374
OAKLEY                            11276
WINTON HILLS                      10637
MT. AIRY                          10362
EVANSTON                          10310
CORRYVILLE                        10120
BOND HILL                          9758
MT. WASHINGTON                     9637
HARTWELL                           9216
CLIFTON                            8536
NORTHSIDE                          8073
QUEENSGATE                         7704
MT. AUBURN                         7630
PLEASANT RIDGE                     6992
SOUTH FAIRMOUNT                    6901
HYDE PARK                          6490
CAMP WASHINGTON                    5885
NORTH AVONDALE - PADDOCK HILLS     5802
EAST WESTWOOD                      4866
CARTHAGE                           4781
SPRING GROVE VILLAGE               4494
MILLVALE                           4288
KENNEDY HEIGHTS                    4076
RIVERSIDE                          4066
VILLAGES AT ROLL HILL              3988
EAST WALNUT HILLS                  3668
PENDLETON                          3418
LOWER PRICE HILL                   3401
NORTH FAIRMOUNT                    3174
SAYLER PARK                        2766
LINWOOD                            2155
EAST END                           2127
SOUTH CUMMINSVILLE                 2073
MT. LOOKOUT                        1459
MT. ADAMS                          1240
ENGLISH WOODS                      1142
SEDAMSVILLE                         865
CALIFORNIA                          822
COLUMBIA TUSCULUM                   509
Name: neighborhood, dtype: int64